//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UT.SL.Model.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class App_Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App_Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UT.SL.Model.Resource.App_Errors", typeof(App_Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to action not found.
        /// </summary>
        public static string BprActionNotFound {
            get {
                return ResourceManager.GetString("BprActionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date can&apos;t be before or same start date.
        /// </summary>
        public static string BprDateSoon {
            get {
                return ResourceManager.GetString("BprDateSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate input.
        /// </summary>
        public static string BprDupInput {
            get {
                return ResourceManager.GetString("BprDupInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main unknown Error.
        /// </summary>
        public static string BprMainUnknownError {
            get {
                return ResourceManager.GetString("BprMainUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong action code.
        /// </summary>
        public static string BprWrongActionCode {
            get {
                return ResourceManager.GetString("BprWrongActionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChooseGroupsToShareWith.
        /// </summary>
        public static string ChooseGroupsToShareWith {
            get {
                return ResourceManager.GetString("ChooseGroupsToShareWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose at least one receiver.
        /// </summary>
        public static string ChooseReceivers {
            get {
                return ResourceManager.GetString("ChooseReceivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is deleted.
        /// </summary>
        public static string DeletedAccount {
            get {
                return ResourceManager.GetString("DeletedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate email.
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateUserName.
        /// </summary>
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format error.
        /// </summary>
        public static string EmailFormatError {
            get {
                return ResourceManager.GetString("EmailFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string FieldIsRequired {
            get {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to format {0} is wrong.
        /// </summary>
        public static string FormatError {
            get {
                return ResourceManager.GetString("FormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password.
        /// </summary>
        public static string InvalidUserPassword {
            get {
                return ResourceManager.GetString("InvalidUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum length is 10{0} letter.
        /// </summary>
        public static string MaxLength10 {
            get {
                return ResourceManager.GetString("MaxLength10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum length is 128{0} letter.
        /// </summary>
        public static string MaxLength128 {
            get {
                return ResourceManager.GetString("MaxLength128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum length is 20{0} letter.
        /// </summary>
        public static string MaxLength20 {
            get {
                return ResourceManager.GetString("MaxLength20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum length is 200{0} letter.
        /// </summary>
        public static string MaxLength200 {
            get {
                return ResourceManager.GetString("MaxLength200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum length is 300{0} letter.
        /// </summary>
        public static string MaxLength300 {
            get {
                return ResourceManager.GetString("MaxLength300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maximum length is 500{0} letter.
        /// </summary>
        public static string MaxLength500 {
            get {
                return ResourceManager.GetString("MaxLength500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails don&apos;t match.
        /// </summary>
        public static string NoMatchEmail {
            get {
                return ResourceManager.GetString("NoMatchEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match.
        /// </summary>
        public static string NoMathPassword {
            get {
                return ResourceManager.GetString("NoMathPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object id missing.
        /// </summary>
        public static string ObjectIdMissing {
            get {
                return ResourceManager.GetString("ObjectIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between 0 and 100.
        /// </summary>
        public static string Range0To100 {
            get {
                return ResourceManager.GetString("Range0To100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not Active, contact Admin.
        /// </summary>
        public static string UnactiveAccount {
            get {
                return ResourceManager.GetString("UnactiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You forgot tp write the message!.
        /// </summary>
        public static string YouForgotToWriteTheMessage {
            get {
                return ResourceManager.GetString("YouForgotToWriteTheMessage", resourceCulture);
            }
        }
    }
}
