//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UT.SL.Model.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class App_Headers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App_Headers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UT.SL.Model.Resource.App_Headers", typeof(App_Headers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed by.
        /// </summary>
        public static string App_User {
            get {
                return ResourceManager.GetString("App_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachement.
        /// </summary>
        public static string Attachement {
            get {
                return ResourceManager.GetString("Attachement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning message.
        /// </summary>
        public static string BeginningMessage {
            get {
                return ResourceManager.GetString("BeginningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birsth date.
        /// </summary>
        public static string BirsthDate {
            get {
                return ResourceManager.GetString("BirsthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change date.
        /// </summary>
        public static string ChangeDate {
            get {
                return ResourceManager.GetString("ChangeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change text.
        /// </summary>
        public static string ChangeText {
            get {
                return ResourceManager.GetString("ChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answer.
        /// </summary>
        public static string CorrectAnsver {
            get {
                return ResourceManager.GetString("CorrectAnsver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creat date.
        /// </summary>
        public static string CreatDate {
            get {
                return ResourceManager.GetString("CreatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create date.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        public static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downvote count.
        /// </summary>
        public static string DownvoteCount {
            get {
                return ResourceManager.GetString("DownvoteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due date.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective score.
        /// </summary>
        public static string EffectiveScore {
            get {
                return ResourceManager.GetString("EffectiveScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File content.
        /// </summary>
        public static string FileContent {
            get {
                return ResourceManager.GetString("FileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From line.
        /// </summary>
        public static string FromeLine {
            get {
                return ResourceManager.GetString("FromeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From letter.
        /// </summary>
        public static string FromLetter {
            get {
                return ResourceManager.GetString("FromLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From page.
        /// </summary>
        public static string FromPage {
            get {
                return ResourceManager.GetString("FromPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HyperLink.
        /// </summary>
        public static string HyperLink {
            get {
                return ResourceManager.GetString("HyperLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is admin.
        /// </summary>
        public static string IsAdmin {
            get {
                return ResourceManager.GetString("IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is circle admin.
        /// </summary>
        public static string IsCircleAdmin {
            get {
                return ResourceManager.GetString("IsCircleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is deleted.
        /// </summary>
        public static string IsDeleted {
            get {
                return ResourceManager.GetString("IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is effective.
        /// </summary>
        public static string IsEffective {
            get {
                return ResourceManager.GetString("IsEffective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login.
        /// </summary>
        public static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update.
        /// </summary>
        public static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max grade.
        /// </summary>
        public static string MaxGrade {
            get {
                return ResourceManager.GetString("MaxGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message count.
        /// </summary>
        public static string MessageCount {
            get {
                return ResourceManager.GetString("MessageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent message thread.
        /// </summary>
        public static string MessageThread {
            get {
                return ResourceManager.GetString("MessageThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min grade.
        /// </summary>
        public static string MinGrade {
            get {
                return ResourceManager.GetString("MinGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object type.
        /// </summary>
        public static string ObjectType {
            get {
                return ResourceManager.GetString("ObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipnients.
        /// </summary>
        public static string Recipnients_App_User {
            get {
                return ResourceManager.GetString("Recipnients_App_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippest.
        /// </summary>
        public static string Snippest {
            get {
                return ResourceManager.GetString("Snippest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titile.
        /// </summary>
        public static string Titile {
            get {
                return ResourceManager.GetString("Titile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To letter.
        /// </summary>
        public static string ToLetter {
            get {
                return ResourceManager.GetString("ToLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To line.
        /// </summary>
        public static string ToLine {
            get {
                return ResourceManager.GetString("ToLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To page.
        /// </summary>
        public static string ToPage {
            get {
                return ResourceManager.GetString("ToPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up down.
        /// </summary>
        public static string Updown {
            get {
                return ResourceManager.GetString("Updown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up vote count.
        /// </summary>
        public static string UpvoteCount {
            get {
                return ResourceManager.GetString("UpvoteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View count.
        /// </summary>
        public static string ViewCount {
            get {
                return ResourceManager.GetString("ViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xcoord.
        /// </summary>
        public static string Xcoord {
            get {
                return ResourceManager.GetString("Xcoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ycoord.
        /// </summary>
        public static string Ycoord {
            get {
                return ResourceManager.GetString("Ycoord", resourceCulture);
            }
        }
    }
}
