//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UT.SL.Model.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AssignmentSubmission {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssignmentSubmission() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UT.SL.Model.Resource.AssignmentSubmission", typeof(AssignmentSubmission).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have able now to create new idea based on my mastery of the subject.
        /// </summary>
        public static string I_have_able_now_to_create_new_idea_based_on_my_mastery_of_the_subject {
            get {
                return ResourceManager.GetString("I_have_able_now_to_create_new_idea_based_on_my_mastery_of_the_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have some ambiguty.
        /// </summary>
        public static string I_have_some_ambiguty {
            get {
                return ResourceManager.GetString("I_have_some_ambiguty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have understand one concept.
        /// </summary>
        public static string I_have_understand_one_concept {
            get {
                return ResourceManager.GetString("I_have_understand_one_concept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have understand some concepts.
        /// </summary>
        public static string I_have_understand_some_concepts {
            get {
                return ResourceManager.GetString("I_have_understand_some_concepts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have understand some concepts and their relationships.
        /// </summary>
        public static string I_have_understand_some_concepts_and_their_relationships {
            get {
                return ResourceManager.GetString("I_have_understand_some_concepts_and_their_relationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The studend has understand some concepts and their relationships.
        /// </summary>
        public static string The_studend_has_understand_some_concepts_and_their_relationships {
            get {
                return ResourceManager.GetString("The_studend_has_understand_some_concepts_and_their_relationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The student has some ambiguty.
        /// </summary>
        public static string The_student_has_some_ambiguty {
            get {
                return ResourceManager.GetString("The_student_has_some_ambiguty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The student has understand one concept.
        /// </summary>
        public static string The_student_has_understand_one_concept {
            get {
                return ResourceManager.GetString("The_student_has_understand_one_concept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The student has understand some concepts.
        /// </summary>
        public static string The_student_has_understand_some_concepts {
            get {
                return ResourceManager.GetString("The_student_has_understand_some_concepts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The student is able now to create new idea based on his/her mastery of the subject.
        /// </summary>
        public static string The_student_is_able_now_to_create_new_idea_based_on_my_mastery_of_the_subject {
            get {
                return ResourceManager.GetString("The_student_is_able_now_to_create_new_idea_based_on_my_mastery_of_the_subject", resourceCulture);
            }
        }
    }
}
