//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UT.SL.Model.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageThread {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageThread() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UT.SL.Model.Resource.MessageThread", typeof(MessageThread).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning message.
        /// </summary>
        public static string BeginningMessage {
            get {
                return ResourceManager.GetString("BeginningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creat date.
        /// </summary>
        public static string CreatDate {
            get {
                return ResourceManager.GetString("CreatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder id.
        /// </summary>
        public static string FolderId {
            get {
                return ResourceManager.GetString("FolderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid id.
        /// </summary>
        public static string GuidId {
            get {
                return ResourceManager.GetString("GuidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update.
        /// </summary>
        public static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message count.
        /// </summary>
        public static string MessageCount {
            get {
                return ResourceManager.GetString("MessageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent message thread.
        /// </summary>
        public static string ParentMessageThread {
            get {
                return ResourceManager.GetString("ParentMessageThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipnients App_User.
        /// </summary>
        public static string Recipnients_App_User {
            get {
                return ResourceManager.GetString("Recipnients_App_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippest.
        /// </summary>
        public static string Snippest {
            get {
                return ResourceManager.GetString("Snippest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id App_User.
        /// </summary>
        public static string UserId_App_User {
            get {
                return ResourceManager.GetString("UserId_App_User", resourceCulture);
            }
        }
    }
}
