//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UT.SL.Data.LINQ.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.8.1,1433;Initial Catalog=SocialLearning;User ID=p.nasirifard;" +
            "Password=master")]
        public string SocialLearningConnectionString {
            get {
                return ((string)(this["SocialLearningConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WINDOWS-913EOWK;Initial Catalog=SocialLearning;User ID=p.nasirifard;P" +
            "assword=master")]
        public string SocialLearningConnectionString1 {
            get {
                return ((string)(this["SocialLearningConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.8.1;Initial Catalog=SocialLearning;Persist Security Info=True" +
            ";User ID=p.nasirifard;Password=master")]
        public string SocialLearningConnectionString2 {
            get {
                return ((string)(this["SocialLearningConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WINDOWS-913EOWK;Initial Catalog=SocialLearning;Persist Security Info=" +
            "True;User ID=p.nasirifard;Password=master")]
        public string SocialLearningConnectionString3 {
            get {
                return ((string)(this["SocialLearningConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=panel1.rackset.com\\SQL2K8R2,14833;Initial Catalog=u643_SLRN;User ID=u" +
            "643_admin;Password=MasterAdmin%2012")]
        public string u643_SLRNConnectionString {
            get {
                return ((string)(this["u643_SLRNConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=OROOJI-PC;Initial Catalog=SocialLearning;Integrated Security=True")]
        public string SocialLearningConnectionString4 {
            get {
                return ((string)(this["SocialLearningConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.8.1,1433;Initial Catalog=SocialLearning;Persist Security Info" +
            "=True;User ID=p.nasirifard;Password=master")]
        public string SocialLearningConnectionString5 {
            get {
                return ((string)(this["SocialLearningConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=EPEZHMAN-PC\\SQLEXPRESS;Initial Catalog=SocialLearning;Integrated Secu" +
            "rity=True")]
        public string SocialLearningConnectionString6 {
            get {
                return ((string)(this["SocialLearningConnectionString6"]));
            }
        }
    }
}
